import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";

//typing animation
// <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>

//ex
//  var typingEffect = new Typed(".djangoText", {
 // strings: ["Django"],
 // loop: true,
 // typeSpeed: 120,
  //backSpeed: 80,
  //backDelay: 1500,
//})

//
import ProfilePic from "../../public/images/profile/developer-pic-1.png";

//components
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title className=" font-bold">Nathaniel E. Adama</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-black w-full min-h-screen ">
        <Layout className={` pt-0`}>
          <div className={`flex justify-between items-center w-full `}>
            <div className=" w-1/2 ">
              <Image src={ProfilePic} alt="nathan" className=" w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center  h-[100%]">
           
              <AnimatedText text={" I am a full stack developer"} className=" py-7 !text-6xl !text-left pl-0"/>
              <p className="my-2 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
