import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";

//
import { useEffect } from "react";

//
import Typed from "typed.js";

import Link from "next/link";



//
import ProfilePic from "../../public/images/profile/developer-pic-1.png";

//components
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {


  //  useEffect(() => {
  //   new Typed('.developerText', {
  //     strings: ['Developer'],
  //     loop: true,
  //     typeSpeed: 120,
  //     backSpeed: 80,
  //     backDelay: 1500,
  //   });
  // }, []);

  return (
    <>
      <Head>
        <title className=" font-bold">Nathaniel E. Adama</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-black w-full min-h-screen  ">
        <Layout className={``}>
          <div className={`flex justify-between items-center w-full `}>
            <div className=" w-1/2 ">
              <Image src={ProfilePic} alt="nathan" className=" w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center  h-[100%]">
           
              <AnimatedText text={" I am a full stack developer"} className=" py-7 !text-6xl !text-left pl-0"/>
              <p className="my-2 text-base font-medium ">
                As a skilled full-stack <span className="developerText">Developer</span>, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
                <div className="flex items-center self-start"> 
                  <Link href="/dummy" target={"_blank"} className=" bg-gray-900 text-white p-3 rounded-md">
                    Resume
                  </Link>
                  <Link href="kvngnathan8420@gmail.com" className="">
                    Contact
                  </Link>
                </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
